plugins:
  - jekyll-seo-tag

title: KAPSARC Energy Model
author: King Abdullah Petroleum Studies and Research Center
description: KEM, KAPSARC, economic model, economics, energy, energy economics
mathjax: true